In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
from sklearn.linear_model import LogisticRegression

In [5]:
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [11]:
df = sns.load_dataset("titanic")
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [12]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [14]:
df.shape

(891, 15)

In [16]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [18]:
df['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [20]:
df.groupby('sex')['age'].median()

sex
female    27.0
male      29.0
Name: age, dtype: float64

In [21]:
df['age'] = df['age'].fillna(df['sex'].map(df.groupby('sex')['age'].median()))
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [22]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [23]:
df['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [24]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [25]:
df['embarked'] =df['embarked'].fillna("S")
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [26]:
df.drop(columns=['deck','alive','embark_town','class'],inplace=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,who,adult_male,alone
0,0,3,male,22.0,1,0,7.2500,S,man,True,False
1,1,1,female,38.0,1,0,71.2833,C,woman,False,False
2,1,3,female,26.0,0,0,7.9250,S,woman,False,True
3,1,1,female,35.0,1,0,53.1000,S,woman,False,False
4,0,3,male,35.0,0,0,8.0500,S,man,True,True

In [27]:
df=pd.get_dummies(df,columns=['who'],drop_first=True)

In [28]:
df=pd.get_dummies(df,columns=['embarked'],drop_first=True)# one hot encoding(It converts categorical/text data into binary (0/1) vectors.)
df['sex']=df['sex'].map({'male':0,'female':1})
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,alone,who_man,who_woman,embarked_Q,embarked_S
0,0,3,0,22.0,1,0,7.2500,True,False,True,False,False,True
1,1,1,1,38.0,1,0,71.2833,False,False,False,True,False,False
2,1,3,1,26.0,0,0,7.9250,False,True,False,True,False,True
3,1,1,1,35.0,1,0,53.1000,False,False,False,True,False,True
4,0,3,0,35.0,0,0,8.0500,True,True,True,False,False,True

In [35]:
X=df.drop(columns=['survived'])
y = df['survived']
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,alone,who_man,who_woman,embarked_Q,embarked_S
0,0,3,0,22.0,1,0,7.2500,True,False,True,False,False,True
1,1,1,1,38.0,1,0,71.2833,False,False,False,True,False,False
2,1,3,1,26.0,0,0,7.9250,False,True,False,True,False,True
3,1,1,1,35.0,1,0,53.1000,False,False,False,True,False,True
4,0,3,0,35.0,0,0,8.0500,True,True,True,False,False,True

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    int64
 3   age         891 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   adult_male  891 non-null    bool
 8   alone       891 non-null    bool
 9   who_man     891 non-null    bool
 10  who_woman   891 non-null    bool
 11  embarked_Q  891 non-null    bool
 12  embarked_S  891 non-null    bool
dtypes: bool(6), float64(2), int64(5)
memory usage: 54.1 KB

In [36]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state= 42,stratify=y)

In [37]:
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [41]:
print("accuracy is",accuracy_score(y_test,y_pred))
print("precision is",precision_score(y_test,y_pred))
print("recall is",recall_score(y_test,y_pred))
print("f1 is",f1_score(y_test,y_pred))
print("Classification report is",classification_report(y_test,y_pred))
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred))

accuracy is 0.8324022346368715
precision is 0.8095238095238095
recall is 0.7391304347826086
f1 is 0.7727272727272727
Classification report is               precision    recall  f1-score   support

           0       0.84      0.89      0.87       110
           1       0.81      0.74      0.77        69

    accuracy                           0.83       179
   macro avg       0.83      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

Confusion Matrix
 [[98 12]
 [18 51]]

In [42]:
!pip install gradio

Defaulting to user installation because normal site-packages is not writeable
Collecting gradio
  Downloading gradio-6.19.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (4.12.1)
Collecting audioop-lts<=0.2.2 (from gradio)
  Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl.metadata (2.0 kB)
Collecting brotli>=1.1.0 (from gradio)
  Downloading brotli-1.2.0-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.138.0-py3-none-any.whl.metadata (27 kB)
Collecting gradio-client==2.5.0 (from gradio)
  Downloading gradio_client-2.5.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Collecting hf-gradio<1.0,>=0.4.1 (from gradio)
  Downloading hf_gradio-0.4.1-py3-none-any.whl.metadata (428 bytes)
Requirement already satisfied: httpx<1.0,>=0.24.1 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (0.28.1)
Collecting huggingface-hub<2.0,>=1.2.0 (from gradio)
  Downloading huggingface_hub-1.20.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: jinja2<4.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (2.4.3)
Collecting orjson~=3.0 (from gradio)
  Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: packaging in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (26.0)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (12.0.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.12.4)
Collecting pydub<1.0 (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart<1.0,>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: pytz>=2017.2 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (6.0.3)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Downloading safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<2.0,>=1.0.1 (from gradio)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.20.0)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from gradio) (4.15.0)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.49.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from gradio-client==2.5.0->gradio) (2025.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\programdata\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi<1.0,>=0.115.2->gradio)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: certifi in c:\users\ritik\appdata\roaming\python\python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\ritik\appdata\roaming\python\python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Collecting click>=8.4.0 (from huggingface-hub<2.0,>=1.2.0->gradio)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (3.20.0)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub<2.0,>=1.2.0->gradio)
  Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: tqdm>=4.42.1 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from pandas<4.0,>=1.0->gradio) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\programdata\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: shellingham>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (14.2.0)
Requirement already satisfied: colorama in c:\users\ritik\appdata\roaming\python\python313\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.2.0->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ritik\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-6.19.0-py3-none-any.whl (31.3 MB)
   ---------------------------------------- 0.0/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/31.3 MB ? eta -:--:--
    --------------------------------------- 0.5/31.3 MB 99.7 kB/s eta 0:05:09
   - -------------------------------------- 0.8/31.3 MB 178.9 kB/s eta 0:02:51
   - -------------------------------------- 1.0/31.3 MB 253.8 kB/s eta 0:02:00
   - -------------------------------------- 1.0/31.3 MB 253.8 kB/s eta 0:02:00
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   - -------------------------------------- 1.3/31.3 MB 290.0 kB/s eta 0:01:44
   -- ------------------------------------- 1.6/31.3 MB 226.9 kB/s eta 0:02:11
   -- ------------------------------------- 1.6/31.3 MB 226.9 kB/s eta 0:02:11
   -- ------------------------------------- 1.6/31.3 MB 226.9 kB/s eta 0:02:11
   -- ------------------------------------- 1.6/31.3 MB 226.9 kB/s eta 0:02:11
   -- ------------------------------------- 1.8/31.3 MB 234.9 kB/s eta 0:02:06
   -- ------------------------------------- 1.8/31.3 MB 234.9 kB/s eta 0:02:06
   -- ------------------------------------- 1.8/31.3 MB 234.9 kB/s eta 0:02:06
   -- ------------------------------------- 1.8/31.3 MB 234.9 kB/s eta 0:02:06
   -- ------------------------------------- 2.1/31.3 MB 241.5 kB/s eta 0:02:01
   -- ------------------------------------- 2.1/31.3 MB 241.5 kB/s eta 0:02:01
   -- ------------------------------------- 2.1/31.3 MB 241.5 kB/s eta 0:02:01
   -- ------------------------------------- 2.1/31.3 MB 241.5 kB/s eta 0:02:01
   -- ------------------------------------- 2.1/31.3 MB 241.5 kB/s eta 0:02:01
   --- ------------------------------------ 2.4/31.3 MB 243.0 kB/s eta 0:02:00
   --- ------------------------------------ 2.6/31.3 MB 265.0 kB/s eta 0:01:49
   --- ------------------------------------ 2.6/31.3 MB 265.0 kB/s eta 0:01:49
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   --- ------------------------------------ 2.9/31.3 MB 286.1 kB/s eta 0:01:40
   ---- ----------------------------------- 3.1/31.3 MB 253.1 kB/s eta 0:01:52
   ---- ----------------------------------- 3.1/31.3 MB 253.1 kB/s eta 0:01:52
   ---- ----------------------------------- 3.1/31.3 MB 253.1 kB/s eta 0:01:52
   ---- ----------------------------------- 3.1/31.3 MB 253.1 kB/s eta 0:01:52
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.4/31.3 MB 259.1 kB/s eta 0:01:48
   ---- ----------------------------------- 3.7/31.3 MB 249.5 kB/s eta 0:01:51
   ----- ---------------------------------- 3.9/31.3 MB 263.4 kB/s eta 0:01:44
   ----- ---------------------------------- 4.2/31.3 MB 276.6 kB/s eta 0:01:38
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ----- ---------------------------------- 4.5/31.3 MB 292.6 kB/s eta 0:01:32
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------ --------------------------------- 5.0/31.3 MB 284.2 kB/s eta 0:01:33
   ------- -------------------------------- 5.5/31.3 MB 289.1 kB/s eta 0:01:30
   ------- -------------------------------- 6.0/31.3 MB 313.8 kB/s eta 0:01:21
   -------- ------------------------------- 6.6/31.3 MB 338.4 kB/s eta 0:01:14
   --------- ------------------------------ 7.1/31.3 MB 361.9 kB/s eta 0:01:07
   --------- ------------------------------ 7.6/31.3 MB 385.7 kB/s eta 0:01:02
   ---------- ----------------------------- 8.1/31.3 MB 409.1 kB/s eta 0:00:57
   ---------- ----------------------------- 8.4/31.3 MB 418.9 kB/s eta 0:00:55
   ----------- ---------------------------- 8.7/31.3 MB 427.6 kB/s eta 0:00:53
   ----------- ---------------------------- 8.9/31.3 MB 437.8 kB/s eta 0:00:52
   ------------ --------------------------- 9.7/31.3 MB 468.6 kB/s eta 0:00:47
   ------------- -------------------------- 10.2/31.3 MB 491.6 kB/s eta 0:00:43
   -------------- ------------------------- 11.0/31.3 MB 524.5 kB/s eta 0:00:39
   --------------- ------------------------ 11.8/31.3 MB 556.5 kB/s eta 0:00:36
   --------------- ------------------------ 12.3/31.3 MB 576.6 kB/s eta 0:00:33
   ---------------- ----------------------- 13.1/31.3 MB 607.0 kB/s eta 0:00:30
   ----------------- ---------------------- 13.6/31.3 MB 626.0 kB/s eta 0:00:29
   ------------------ --------------------- 14.4/31.3 MB 656.6 kB/s eta 0:00:26
   ------------------- -------------------- 14.9/31.3 MB 674.9 kB/s eta 0:00:25
   ------------------- -------------------- 15.5/31.3 MB 690.9 kB/s eta 0:00:23
   -------------------- ------------------- 16.0/31.3 MB 709.9 kB/s eta 0:00:22
   --------------------- ------------------ 16.5/31.3 MB 727.0 kB/s eta 0:00:21
   ---------------------- ----------------- 17.3/31.3 MB 753.2 kB/s eta 0:00:19
   ---------------------- ----------------- 17.8/31.3 MB 769.3 kB/s eta 0:00:18
   ----------------------- ---------------- 18.1/31.3 MB 773.7 kB/s eta 0:00:18
   ----------------------- ---------------- 18.4/31.3 MB 778.7 kB/s eta 0:00:17
   ----------------------- ---------------- 18.6/31.3 MB 781.6 kB/s eta 0:00:17
   ----------------------- ---------------- 18.6/31.3 MB 781.6 kB/s eta 0:00:17
   ------------------------ --------------- 19.1/31.3 MB 793.8 kB/s eta 0:00:16
   ------------------------- -------------- 19.7/31.3 MB 808.3 kB/s eta 0:00:15
   -------------------------- ------------- 20.4/31.3 MB 832.3 kB/s eta 0:00:14
   -------------------------- ------------- 20.7/31.3 MB 839.1 kB/s eta 0:00:13
   --------------------------- ------------ 21.2/31.3 MB 850.2 kB/s eta 0:00:12
   --------------------------- ------------ 21.8/31.3 MB 864.8 kB/s eta 0:00:12
   ---------------------------- ----------- 22.5/31.3 MB 887.0 kB/s eta 0:00:10
   ----------------------------- ---------- 23.1/31.3 MB 900.8 kB/s eta 0:00:10
   ------------------------------ --------- 23.9/31.3 MB 923.2 kB/s eta 0:00:09
   ------------------------------ --------- 23.9/31.3 MB 923.2 kB/s eta 0:00:09
   ------------------------------ --------- 24.1/31.3 MB 924.4 kB/s eta 0:00:08
   ------------------------------- -------- 24.9/31.3 MB 940.7 kB/s eta 0:00:07
   -------------------------------- ------- 25.4/31.3 MB 954.1 kB/s eta 0:00:07
   --------------------------------- ------ 26.0/31.3 MB 965.4 kB/s eta 0:00:06
   ---------------------------------- ----- 26.7/31.3 MB 987.7 kB/s eta 0:00:05
   ---------------------------------- ----- 27.3/31.3 MB 998.8 kB/s eta 0:00:05
   ----------------------------------- ---- 27.5/31.3 MB 1.0 MB/s eta 0:00:04
   ----------------------------------- ---- 27.8/31.3 MB 1.0 MB/s eta 0:00:04
   ----------------------------------- ---- 27.8/31.3 MB 1.0 MB/s eta 0:00:04
   ----------------------------------- ---- 27.8/31.3 MB 1.0 MB/s eta 0:00:04
   ----------------------------------- ---- 28.0/31.3 MB 991.5 kB/s eta 0:00:04
   ------------------------------------ --- 28.3/31.3 MB 992.9 kB/s eta 0:00:03
   ------------------------------------ --- 28.6/31.3 MB 996.9 kB/s eta 0:00:03
   ------------------------------------- -- 29.1/31.3 MB 1.0 MB/s eta 0:00:03
   ------------------------------------- -- 29.6/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 30.1/31.3 MB 1.0 MB/s eta 0:00:02

  WARNING: The script uvicorn.exe is installed in 'C:\Users\ritik\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script fastapi.exe is installed in 'C:\Users\ritik\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts hf.exe, huggingface-cli.exe and tiny-agents.exe are installed in 'C:\Users\ritik\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script hf-gradio.exe is installed in 'C:\Users\ritik\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts gradio.exe and upload_theme.exe are installed in 'C:\Users\ritik\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires packaging<26,>=20, but you have packaging 26.0 which is incompatible.

In [46]:
import gradio as gr
import pandas as pd

def predict_fn(*values):
    data = pd.DataFrame([values], columns=X.columns)
    pred = model.predict(data)[0]
    
    if pred == 1:
        return "Survived"
    else:
        return "Not Survived"

app = gr.Interface(
    fn=predict_fn,
    inputs=[gr.Number(label=col) for col in X.columns],
    outputs="text",
    title="TITANIC Survival Prediction"
)

app.launch(share=True)

* Running on local URL:  http://127.0.0.1:7861
* Running on public URL: https://1fa13f8e5e203bee37.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

C:\Users\ritik\AppData\Roaming\Python\Python313\site-packages\gradio\routes.py:1379: StarletteDeprecationWarning: 'HTTP_422_UNPROCESSABLE_ENTITY' is deprecated. Use 'HTTP_422_UNPROCESSABLE_CONTENT' instead.
  return await queue_join_helper(body, request, username)